version: "4"
services:
  db:
    container_name: "PostgreSQL"
    image: "postgres:14.2"
    ports: 
      - "5433:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    networks:
      - default
  webapp:
    container_name: "Node"
    restart: always
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
networks:
  default:
volumes:
  pgdata : {}