version: "4"
services:
  server:
    container_name: "Node"
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - database
  database:
    container_name: "PostgreSQL"
    image: "postgres:14.2"
    ports: 
      - "5433:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
volumes:
  pgdata : {}