version: "4"
services:
  db:
    container_name: "postgresql"
    image: "postgres:14.2"
    ports: 
      - "5433:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challange
    networks:
      - default
networks:
  default:
volumes:
  pgdata : {}